#! /bin/sh

bspc config border_width            2
bspc config window_gap              12

#bspc config focused_border_color    "#a7a7a7"
#bspc config normal_border_color     "#333232"
bspc config presel_feedback_color   "#333232"

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config single_monocle	        true
bspc config gapless_monocle         true
bspc config focus_by_distance       true
bspc config history_aware_focus     true

feh --bg-scale ~/.wallpaper.png

bspc monitor -d I II III IV V VI VII VIII IX X

#bscp rule -a urxvt state=floating
#bspc rule -a chromium desktop=^2 follow=on