#! /bin/sh

bspc config border_width            2
bspc config window_gap              24
bspc config top_padding             20

bspc config focused_border_color    "#AD2BEE"
bspc config normal_border_color     "#2E3436"
bspc config presel_feedback_color   "#AD2BEE"

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config single_monocle	        true
bspc config gapless_monocle         true
bspc config focus_by_distance       true
bspc config history_aware_focus     true
 
bspc config click_to_focus	    true

feh --bg-scale ~/.wallpaper.png

bspc monitor -d I II III IV V

#bscp rule -a urxvt state=floating
#bspc rule -a chromium desktop=^2 follow=on
