#! /bin/sh

#
# wm independent hotkeys
#

# terminal emulator
super + Return
	urxvt

# program launcher
alt + space
	dmenu_run -i

# make sxhkd reload its configuration files:
super + F5
	pkill -USR1 -x sxhkd

Print
	scrot ~/pictures/screenshots/%y-%m-%d-%T.png

#
# bspwm hotkeys
#

# quit bspwm normally
super + Escape
	pkill -x panel; bspc quit

# close and kill
super + {_,shift + }d
	bspc node -{c,k}

# alternate between the tiled and monocle layout
super + a
	bspc desktop -l next

# swap the current node and the biggest node
super + z 
	bspc node -s biggest

#
# state/flags
#

# set the window state
super + {x,shift + x,s,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

#
# focus/swap
#

# focus the node in the given direction
super + {_,shift + }{Left,Down,Up,Right}
	bspc node -{f,s} {west,south,north,east}

# focus the next/previous node
super + {_,shift + }Tab
	bspc node -f {next,prev}

# focus the next/previous desktop
super + ctrl + {Left,Right}
	bspc desktop -f {prev,next}

# focus or send to the given desktop
super + {_,ctrl + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

#
# preselect
#

# preselect the direction
super + alt + {Left,Down,Up,Right}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + alt + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + alt + 0
	bspc node -p cancel

#
# pointer focus/move/resize
#

# focus
~button1
	bspc pointer -g focus

# start move/resize
super + button{1-3}
	; bspc pointer -g {move,resize_side,resize_corner}

# end move/resize
super + @button{1-3}
	bspc pointer -u

# change windows gap
super + {minus,equal}
	bspc config -d focused window_gap $((`bspc config -d focused window_gap`{+,-} 2))

#
# volume control
#

XF86AudioRaiseVolume
	sh -c "pactl set-sink-mute 1 false ; pactl set-sink-volume 1 +5%"

XF86AudioLowerVolume
	sh -c "pactl set-sink-mute 1 false ; pactl set-sink-volume 1 -5%"

XF86AudioMute
	pactl set-sink-mute 1 toggle